#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"

		delete system.ntp.server
		add_list system.ntp.server="ntp.tencent.com"
		add_list system.ntp.server="ntp1.aliyun.com"
		add_list system.ntp.server="ntp.ntsc.ac.cn"
		add_list system.ntp.server="cn.ntp.org.cn"
                add_list system.ntp.server="216.239.35.0"
		add_list system.ntp.server="216.239.35.8"
		add_list system.ntp.server="162.159.200.1"
		add_list system.ntp.server="162.159.200.123"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.vsean.net/openwrt"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"
sed -i -e 's/ImmortalWrt/Openwrt/' -e 's/LuCI [^ ]*/LeeSun/g' -e '/luciversion/d' /usr/lib/lua/luci/version.lua
echo "luciversion ='$(date +'%m.%d')'" >> /usr/lib/lua/luci/version.lua

exit 0
