#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Shanghai"

		delete system.ntp.server
		add_list system.ntp.server="ntp.tencent.com"
		add_list system.ntp.server="ntp1.aliyun.com"
		add_list system.ntp.server="ntp.ntsc.ac.cn"
		add_list system.ntp.server="cn.ntp.org.cn"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://mirrors.vsean.net/openwrt"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"

# 设置配置文件的部署标记（所有文件在构建时已直接部署）
uci -q batch <<-EOF
    set system.@imm_init[0].smartdns_conf="1"
    set system.@imm_init[0].smartdns_cloudflare="1"
    set system.@imm_init[0].smartdns_domainset="1"
    set system.@imm_init[0].microsocks_conf="1"
    set system.@imm_init[0].config_dhcp="1"
    set system.@imm_init[0].config_firewall="1"
    set system.@imm_init[0].config_luci="1"
    set system.@imm_init[0].config_network="1"
    set system.@imm_init[0].config_mosdns="1"
    set system.@imm_init[0].config_system="1"
    set system.@imm_init[0].config_smartdns="1"
    set system.@imm_init[0].config_upnpd="1"
    commit system
EOF

exit 0
