# ===== 核心监听配置（适配二级路由：本地调用+局域网共享） =====
listen_addresses = ['127.0.0.1:5353', '192.168.3.2:5353']  # 127.0.0.1=SmartDNS调用，192.168.3.2=设备直接使用

# ===== 加密与防泄漏配置（关键优化） =====
block_unencrypted = true  # 禁止未加密请求
fallback_resolvers = []   # 禁止备用未加密DNS
filters = [
  { filter = ['doh'], exclude_filter = ['filter'], require_ipv4 = true }  # 筛选DoH、无过滤、IPv4节点
]

# ===== 解析器选择（保留你原有的Cloudflare+Google，结合筛选规则） =====
server_names = ['cloudflare', 'google']

# ===== 缓存配置（保留你的原配置，合理无需改） =====
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

# ===== 日志配置（补充基础日志，避免目录报错） =====
log_file = '/tmp/dnscrypt-proxy2.log'  # 基础启动/错误日志（放/tmp根目录，无需创建）
log_level = 'debug'

[query_log]
  file = '/tmp/dnscrypt-proxy/query.log'  # 详细查询日志
  format = 'tsv'  # 表格格式，易读

[nx_log]
  file = '/tmp/dnscrypt-proxy/nx.log'  # 不存在域名日志

# ===== 解析器列表（保留你的原配置，官方可靠） =====
[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/etc/dnscrypt-proxy2/public-resolvers.md'  # 本地缓存列表，减少重复下载
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'  # 官方验证密钥
  refresh_delay = 72  # 72小时更新一次列表，避免频繁请求
  prefix = ''

# ===== OpenWRT 专属：自动创建日志目录（重启后生效） =====
[openwrt]
pre_init = 'mkdir -p /tmp/dnscrypt-proxy'